{{- if .Values.flink.highavailability.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-aws-credentials
type: Opaque
data:
  aws_access_key_id: {{ .Values.flink.highavailability.aws_access_key_id | b64enc }}
  aws_secret_access_key: {{ .Values.flink.highavailability.aws_secret_access_key | b64enc }}
{{- end }}
